### ISSUE TITLE
Apply types to account data and event data 

### ISSUE THREAD

**Issue by rossbulat** [polkadot-live/polkadot-live-app#19]
Expand on the `EventData` type and use in the main process. We should not use any `Any` types for event data and ensure predictability for the renderer.

The model should also implement concrete types.

**Comment by danebulat** [comment]
Since opening this pull request, the Polkadot Live codebase has seen new types implemented for the events system. 

Making type fields concrete and avoiding the `any` type is a work in progress and will be amended, if necessary, when the codebase and subsystems mature.

Therefore, this issue may be closed
